site_name: PlumPedia
site_url: https://plumpedia.github.io/
repo_url: https://github.com/plumpedia/PlumPedia
docs_dir: 'docs'
theme: 
  name: material
  features:
    - navigation.tracking
extra_css:
  - 'stylesheets/style.css'
