
name: publish

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Mkdocs
        run: |
            cd ..
            git clone https://github.com/plumpedia/PlumPedia.git
            cd PlumPedia
            # install pip=>20.1 to use "pip cache dir"
            python3 -m pip install --upgrade pip
            echo "::set-output name=dir::$(pip cache dir)"
            python3 -m pip install -r ./requirements.txt
            cd ../plumpedia.github.io/
            mkdocs gh-deploy --config-file ../PlumPedia/mkdocs.yml --remote-branch master
